export const CHANNELS = {
  projectCreate: 'video-essay:project:create',
  projectOpen: 'video-essay:project:open',
  projectSave: 'video-essay:project:save',
  projectReload: 'video-essay:project:reload',
  projectReveal: 'video-essay:project:reveal',
  projectChooseImage: 'video-essay:project:choose-image',
  projectImportImage: 'video-essay:project:import-image',
  projectImportRemoteImage: 'video-essay:project:import-remote-image',
  projectImportClipboardImage: 'video-essay:project:import-clipboard-image',
  projectSaveImageBytes: 'video-essay:project:save-image-bytes',
  projectSetDirty: 'video-essay:project:set-dirty',
  projectNewRequested: 'video-essay:project:new-requested',
  projectOpenRequested: 'video-essay:project:open-requested',
  projectSaveRequested: 'video-essay:project:save-requested',
  undoRequested: 'video-essay:edit:undo-requested',
  redoRequested: 'video-essay:edit:redo-requested',
  exportStart: 'video-essay:export:start',
  exportCancel: 'video-essay:export:cancel',
  exportProgress: 'video-essay:export:progress',
  openVideo: 'video-essay:file:open-video',
  showInFinder: 'video-essay:file:show-in-finder',
  renderJob: 'video-essay:render:job',
  renderStart: 'video-essay:render:start',
  renderCalibrationReady: 'video-essay:render:calibration-ready',
  renderReady: 'video-essay:render:ready',
  renderStarted: 'video-essay:render:started',
} as const
