import type { Presentation } from './model'

export const demoPresentation: Presentation = {
  id: 'small-screens',
  title: 'Small Screens, Bigger Questions',
  tagline: 'Ideas. Structure. A more thoughtful internet.',
  aspectRatio: '9:16',
  accent: '#ff554f',
  scenes: [
    {
      id: 'hook',
      type: 'title',
      title: 'The hook',
      duration: 3,
      eyebrow: 'A quiet shift',
      headline: 'Good stories\nstill matter.',
      subtitle: 'Even when the screen fits in your hand.',
      notes: 'Open simply. Let the first line sit for a beat before moving forward.',
      transition: { type: 'fade', duration: 0.55 },
    },
    {
      id: 'landscape',
      type: 'text',
      title: 'A shrinking landscape',
      duration: 4,
      eyebrow: 'The landscape',
      headline: 'A familiar place\nis disappearing.',
      body: 'Independent theaters once anchored main streets. Today, many are fighting to keep the lights on.',
      callout: 'Fewer screens. Fewer shared moments.',
      notes: 'Set the scene. This is about more than ticket sales—it is about civic gathering places.',
      transition: { type: 'slide', duration: 0.65 },
    },
    {
      id: 'stat-reveal',
      type: 'big-stat',
      title: 'Fewer theaters',
      duration: 5,
      eyebrow: 'Small screens · bigger questions',
      value: '42%',
      label: 'fewer independent theaters',
      supportingText: 'Since 2007, the number of independent theaters in our example has fallen sharply.',
      elementId: 'theater-decline-stat',
      notes: 'Land on the number. Pause after “forty-two percent,” then explain the scale of the change.',
      transition: { type: 'scale', duration: 0.7 },
    },
    {
      id: 'stat-context',
      type: 'stat-detail',
      title: 'Why it matters',
      duration: 4,
      eyebrow: 'Not just a number',
      value: '42%',
      label: 'fewer theaters',
      headline: 'A statistic becomes\na street with no marquee.',
      body: 'When a local screen closes, a community loses a place to encounter new ideas together.',
      elementId: 'theater-decline-stat',
      notes: 'The number morphs into context. Connect the abstract statistic to a physical place.',
      transition: { type: 'slide', duration: 0.75 },
    },
    {
      id: 'comparison',
      type: 'comparison',
      title: 'Two futures',
      duration: 5,
      eyebrow: 'The choice',
      headline: 'Convenience grew.\nConnection shrank.',
      left: { label: 'At home', value: '∞' },
      right: { label: 'Together', value: '1' },
      notes: 'Contrast unlimited choice with the singular feeling of watching together.',
      transition: { type: 'fade', duration: 0.55 },
    },
    {
      id: 'resistance',
      type: 'text',
      title: 'The resistance',
      duration: 4,
      eyebrow: 'Still here',
      headline: 'People keep\nit alive.',
      body: 'Programmers, projectionists, and audiences are finding new ways to make the local theater matter.',
      callout: 'The future is participatory.',
      notes: 'Shift the tone toward agency. This is where the story stops being only about decline.',
      transition: { type: 'scale', duration: 0.6 },
    },
    {
      id: 'close',
      type: 'title',
      title: 'The close',
      duration: 3,
      eyebrow: 'A brighter tomorrow',
      headline: 'More human\nstories.',
      subtitle: 'Made for the small screen. Built around big ideas.',
      notes: 'Close with optimism and leave the final line on screen.',
      transition: { type: 'fade', duration: 0.8 },
    },
  ],
}
