import type { LegacyPresentation } from './model'
import { migratePresentationV1ToV2 } from './presentationMigration'

const audienceData = [
  { id: 'horizon', label: 'Horizon', value: 31 },
  { id: 'beacon', label: 'Beacon', value: 26 },
  { id: 'atlas', label: 'Atlas', value: 18 },
  { id: 'common', label: 'Common', value: 11 },
]

const legacySamplePresentation: LegacyPresentation = {
  schemaVersion: 1,
  id: 'chart-story-lab',
  title: 'Chart Story Lab',
  tagline: 'A sample sequence for testing editorial data storytelling.',
  aspectRatio: '9:16',
  accent: '#6c5ce7',
  scenes: [
    {
      id: 'chart-story-title',
      type: 'title',
      title: 'Introduce the dataset',
      duration: 4,
      eyebrow: 'Illustrative data only',
      headline: 'One dataset.\nFour story beats.',
      subtitle: 'Watch stable values persist as the focus changes.',
      notes: 'All names and values in this sample are invented for interface testing.',
      transition: { type: 'fade', duration: 0.55 },
    },
    {
      id: 'chart-story-all',
      type: 'chart',
      title: 'Show the full field',
      duration: 5,
      eyebrow: 'Sample audience share',
      headline: 'The field begins\nwith four players.',
      chartType: 'bar',
      orientation: 'horizontal',
      data: audienceData,
      highlightIds: [],
      valueSuffix: '%',
      showValues: true,
      source: 'Illustrative sample data — not a factual claim',
      supportingText: 'Start with the whole distribution before directing attention.',
      chartId: 'sample-audience-share',
      notes: 'Placeholder data created solely to test chart rendering.',
      transition: { type: 'fade', duration: 0.55 },
    },
    {
      id: 'chart-story-horizon',
      type: 'chart',
      title: 'Highlight Horizon',
      duration: 5,
      eyebrow: 'First focus',
      headline: 'Horizon leads\nthe sample field.',
      chartType: 'bar',
      orientation: 'horizontal',
      data: audienceData,
      highlightIds: ['horizon'],
      valueSuffix: '%',
      showValues: true,
      source: 'Illustrative sample data — not a factual claim',
      supportingText: 'The other values stay visible so the comparison keeps its context.',
      chartId: 'sample-audience-share',
      transition: { type: 'fade', duration: 0.5 },
    },
    {
      id: 'chart-story-atlas',
      type: 'chart',
      title: 'Shift focus to Atlas',
      duration: 5,
      eyebrow: 'Second focus',
      headline: 'Then attention\nshifts to Atlas.',
      chartType: 'bar',
      orientation: 'horizontal',
      data: audienceData,
      highlightIds: ['atlas'],
      valueSuffix: '%',
      showValues: true,
      source: 'Illustrative sample data — not a factual claim',
      supportingText: 'Stable datum IDs let the same bars carry the next beat.',
      chartId: 'sample-audience-share',
      transition: { type: 'fade', duration: 0.5 },
    },
    {
      id: 'chart-story-reorder',
      type: 'chart',
      title: 'Reorder and resize',
      duration: 5,
      eyebrow: 'A hypothetical update',
      headline: 'A new snapshot\nchanges the order.',
      chartType: 'bar',
      orientation: 'horizontal',
      data: [
        { id: 'horizon', label: 'Horizon', value: 32 },
        { id: 'atlas', label: 'Atlas', value: 27 },
        { id: 'beacon', label: 'Beacon', value: 24 },
        { id: 'common', label: 'Common', value: 12 },
      ],
      highlightIds: ['atlas'],
      valueSuffix: '%',
      showValues: true,
      source: 'Illustrative sample data — not a factual claim',
      supportingText: 'The entities persist while their order and values change.',
      chartId: 'sample-audience-share',
      transition: { type: 'slide', duration: 0.65 },
    },
    {
      id: 'chart-story-line',
      type: 'chart',
      title: 'Show a trend',
      duration: 5,
      eyebrow: 'A separate sample series',
      headline: 'Momentum builds\nover five periods.',
      chartType: 'line',
      data: [
        { id: 'period-1', label: 'P1', value: 34 },
        { id: 'period-2', label: 'P2', value: 41 },
        { id: 'period-3', label: 'P3', value: 46 },
        { id: 'period-4', label: 'P4', value: 58 },
        { id: 'period-5', label: 'P5', value: 67 },
      ],
      highlightIds: ['period-5'],
      valueSuffix: '%',
      showValues: true,
      source: 'Illustrative sample data — not a factual claim',
      supportingText: 'A single-series line keeps the trend legible in a vertical frame.',
      chartId: 'sample-momentum-trend',
      transition: { type: 'fade', duration: 0.6 },
    },
    {
      id: 'chart-story-close',
      type: 'text',
      title: 'Close the story',
      duration: 4,
      eyebrow: 'The takeaway',
      headline: 'Show the field.\nThen guide the eye.',
      body: 'Structured data lets one visual argument unfold across several focused scenes.',
      callout: 'Same entities. A clearer story.',
      transition: { type: 'fade', duration: 0.65 },
    },
  ],
}

export const samplePresentation = migratePresentationV1ToV2(legacySamplePresentation)
